package com.itconsult.itconsult.types;

public enum OrderType {
    SECURITY_ARCHITECTURE,
    DATABASE,
    URGENT_SECURITY_PROBLEM,
    HARDWARE,
    SCALABILITY,
    CLOUD,
    INFRASTRUCTURE,
    SOFTWARE_DEVELOPMENT,
    ADMINISTRATION
}
